### PR TITLE
Support ~/.aws/config with instance profile

### PR DESCRIPTION
**Pull request by sonots**
Fix https://github.com/sonots/ec2-host/pull/15#issuecomment-460504160

### CODE REVIEW

**Comment by sonots** [comment]
1.0.2 is released.

**Comment by sonots** [comment]
@toyama0919 can you check assume role is working well?

**Comment by toyama0919** [comment]
>can you check assume role is working well?

Of course!
I'll check assume role.

**Comment by toyama0919** [comment]
not works assume role..

bug fix PR is there.
https://github.com/sonots/ec2-host/pull/18

**Pull request merged**
