### PR TITLE
upgrade aws-sdk v3. use aws-sdk-ec2.

### PR DESCRIPTION
**Pull request by toyama0919**

### CODE REVIEW

**Comment by sonots** [comment]
We should upgrade major version because this change breaks backward compatibility.

**Comment by sonots** [comment]
Let's upgrade to 1.0.0 after merging this.

**Comment by sonots** [comment]
I added you to ec2-host gem owner, please release 1.0.0 by yourself.
After upgrading in VERSION file,

```
bundle exec rake release
```

should work.

**Comment by toyama0919** [comment]
>I added you to ec2-host gem owner, please release 1.0.0 by yourself.
> After upgrading in VERSION file,

OK. Thanks!!!

**Comment by toyama0919** [comment]
released.

https://rubygems.org/gems/ec2-host

**Comment by sonots** [comment]
Thanks!

**Pull request merged**
